// This is a configuration file generated by CMake.
// It provides the root directory path for asset loading.

#ifndef ROOT_DIRECTORY_H
#define ROOT_DIRECTORY_H

const char * logl_root = "D:/gen3dart/";

#endif // ROOT_DIRECTORY_H
